import {bossStats,bossSchedule} from './performance.js';
import {drawPortrait,drawAnimation} from './graphics.js';
import {NEW_CHARACTERS,PETS,BOSSES,MAP_EVENTS,phaseFor} from './content-data.js';
export function createContent(r,battle,weapons){let events=[],lastPet=0,lastEvent=0,lastMid=0,pet='fairy',runGold=0,revived=false,cleared=new Set(),shop=null,shopWasPaused=false;const s=r.state,p=r.player;
 function start(config){closeShop();events=[];lastPet=0;lastEvent=0;lastMid=0;runGold=0;revived=false;cleared=new Set();pet=config.pet||'fairy';spawnEvent('treasure');}
 function spawnEvent(type){if(events.length>=4)return null;const pos=r.randomPointAroundPlayer(180,450),event={...pos,id:crypto.randomUUID(),type,used:false,r:28};events.push(event);return event;}
 function interact(event){if(!event||event.used)return false;if(event.type==='merchant'){openShop(event);return true;}if(event.type==='altar'&&(s.mathEnergy||0)<20){r.showToast('강화 제단은 수학 에너지 20이 필요합니다.');return false;}event.used=true;
  if(event.type==='treasure'){r.spawnItem(event.x,event.y,'chest');r.spawnExpDrops(event.x,event.y,40,3);}
  if(event.type==='altar'){s.mathEnergy-=20;s.attackPower+=7;r.showToast('강화 제단 · 공격력 +7');}
  if(event.type==='secret'){const point=r.randomPointAroundPlayer(450,800);p.x=point.x;p.y=point.y;p.invincible=1500;r.updateCamera();r.spawnItem(p.x+60,p.y,'chest');r.spawnExpDrops(p.x,p.y,75,3);}
  r.sfx('item');return true;
 }
 const goods=[{id:'heal',name:'숲의 수프 · 체력 +50',cost:20,apply(){s.hp=Math.min(s.maxHp,s.hp+50);}},{id:'shield',name:'보호 부적 · 보호막 +2',cost:25,apply(){s.shield=Math.min(8,s.shield+2);}},{id:'energy',name:'별빛 차 · 수학 에너지 +25',cost:25,apply(){s.mathEnergy=Math.min(100,(s.mathEnergy||0)+25);}},{id:'power',name:'힘의 연필 · 패시브 +1',cost:30,apply(){const card=weapons.upgrades().find(x=>x.title.startsWith('힘의 연필'));if(!card)return false;card.apply();}}];
 function closeShop(){if(!shop)return;shop.remove();shop=null;s.merchantOpen=false;s.paused=shopWasPaused;}
 function available(good){if(good.id==='heal')return s.hp<s.maxHp;if(good.id==='shield')return s.shield<8;if(good.id==='energy')return (s.mathEnergy||0)<100;return weapons.upgrades().some(x=>x.title.startsWith('힘의 연필'));}
 function purchase(id){const good=goods.find(g=>g.id===id);if(!shop||!good||runGold<good.cost||!available(good))return false;if(good.apply()===false)return false;runGold-=good.cost;r.sfx('item');closeShop();return true;}
 function openShop(event){if(shop)return;event.used=true;shopWasPaused=s.paused;s.paused=true;s.merchantOpen=true;shop=document.createElement('div');shop.id='merchantPopup';shop.className='overlay';shop.setAttribute('role','dialog');shop.setAttribute('aria-modal','true');shop.setAttribute('aria-label','숲의 상인');shop.innerHTML='<div class="card"><h2>숲의 상인</h2><p>이번 판 골드 '+runGold+' · 상품을 고르는 동안 전투 시간이 멈춥니다.</p><div class="catalogGrid">'+goods.map(g=>'<button data-good="'+g.id+'" '+(runGold<g.cost||!available(g)?'disabled':'')+'>'+g.name+'<br>'+g.cost+'골드</button>').join('')+'</div><button id="closeMerchant">다음에 올게요</button></div>';document.body.append(shop);shop.addEventListener('click',e=>{const button=e.target.closest('[data-good]');if(button)purchase(button.dataset.good);});document.getElementById('closeMerchant').onclick=closeShop;shop.querySelector('button:not(:disabled)').focus();}
 function skill(){const c=NEW_CHARACTERS[s.character];if(!c)return false;const now=r.gameNow();if(c.skill==='dash'){s.speedUntil=now+4500;p.dashCooldown=0;p.invincible=1800;r.explode(p.x,p.y,180,70,true);}if(c.skill==='fan')weapons.attack('protractor',{style:'fan',damage:60,count:13,range:600,pierce:5,color:'#f7b178'},now);if(c.skill==='heal'){s.hp=Math.min(s.maxHp,s.hp+60);s.shield=Math.min(8,s.shield+2);}if(c.skill==='energy'){s.mathEnergy=Math.min(100,s.mathEnergy+20);weapons.attack('quill',{style:'homing',damage:65,count:6,range:700,pierce:2,color:'#c8b9ff'},now);}if(c.skill==='blast')r.explode(p.x,p.y,400,130,true);if(c.skill==='freeze'){s.freezeUntil=now+3500;r.explode(p.x,p.y,230,75,true);}if(c.skill==='meteor')weapons.attack('comet',{style:'rain',damage:110,count:9,range:700,pierce:5,color:'#f2acde'},now);r.showToast(c.name+' 고유 스킬!');r.sfx('level');return true;}
 function petTick(now){if(pet==='fairy')return false;const spec=PETS[pet];if(now-lastPet<spec.period)return true;lastPet=now;const targets=battle.grid.near(p.x,p.y,550);
  if(spec.kind==='heal')s.hp=Math.min(s.maxHp,s.hp+7+s.petLevel);if(spec.kind==='collect')s.magnetUntil=now+1800;if(spec.kind==='shield')s.shield=Math.min(8,s.shield+1);if(spec.kind==='slow')for(const e of targets)e.slowUntil=now+1800;if(spec.kind==='chain')for(const e of targets.slice(0,3))weapons.hit(e,25+s.petLevel*4);if(spec.kind==='attack'&&targets[0]){const e=targets[0],a=Math.atan2(e.y-p.y,e.x-p.x);r.projectiles.push({kind:'pet',x:p.x-50,y:p.y-40,vx:Math.cos(a)*8,vy:Math.sin(a)*8,r:6,damage:14+s.petLevel*5,life:70,pierce:1,color:'#efd785'});}if(spec.kind==='revive')s.hp=Math.min(s.maxHp,s.hp+5);return true;
 }
 function preventDeath(){if(pet==='phoenix'&&!revived&&s.hp<=0){revived=true;s.hp=s.maxHp*.4;p.invincible=3500;r.showToast('지식 불사조가 한 번 되살렸습니다!');return true;}return false;}
 function bossTick(now){for(const e of r.enemies){if(!e.boss)continue;e.phase=phaseFor(e.hp/e.maxHp);if(['forest','desert','library'].includes(e.bossType)&&!e.midBoss)continue;if(now<e.nextPattern||now<s.freezeUntil)continue;e.nextPattern=now+Math.max(1500,3700-e.phase*550);const hazards=r.v2.combat.hazards(),add=h=>hazards.push({...h,fireAt:now+1200,expireAt:now+1850,damage:({easy:9,normal:16,hard:22})[s.difficulty]});
  if(e.midBoss)add({shape:'circle',x:p.x,y:p.y,r:80,label:'중간 보스 충격파'});
  else if(e.bossType==='ocean'){add({shape:'ring',x:e.x,y:e.y,r:140+e.phase*45,width:18,label:'크라켄 물결'});for(let i=0;i<e.phase;i++)add({shape:'circle',x:p.x+i*80,y:p.y,r:70,label:'바다 거품'});}
  else if(e.bossType==='clockwork'){for(let i=0;i<2+e.phase;i++)add({shape:'beam',x:e.x,y:e.y,angle:now/1000+i*Math.PI*2/(2+e.phase),length:700,width:18,label:'시계 바늘'});}
  else{add({shape:'rect',x:p.x,y:p.y,w:320,h:80,label:'하늘 직선'});if(e.phase>1)add({shape:'rect',x:p.x,y:p.y,w:80,h:320,label:'하늘 교차'});if(e.phase===3)add({shape:'circle',x:e.x,y:e.y,r:230,label:'천룡 폭발'});}
 }}
 function midBoss(){if(r.enemies.filter(e=>e.midBoss&&e.hp>0).length>=2)return null;const point=r.randomPointAroundPlayer(550,750),hp=260+s.level*30,e={...point,r:34,...bossStats({hp,speed:.85,damage:14},s.difficulty),elite:true,boss:true,midBoss:true,name:'중간 보스 · 거울 기사',bossType:s.currentMapKey,nextPattern:r.gameNow()+2000,patternIndex:0,wobble:0};r.v3.math.attachBoss(e);r.enemies.push(e);return e;}
 function tick(now){bossTick(now);if(s.mode!=='explore'&&s.mode!=='boss'&&now-lastMid>bossSchedule(s.difficulty).mid*1000){lastMid=now;midBoss();}if(now-lastEvent>45000){lastEvent=now;spawnEvent(Object.keys(MAP_EVENTS)[Math.floor(now/45000)%4]);}for(const event of events)if(!event.used&&r.distance(event,p)<p.r+event.r)interact(event);events=events.filter(e=>!e.used);}
 function killed(e){if(e.boss){runGold+=e.midBoss?20:(BOSSES[e.bossType]?.gold||35);cleared.add(e.midBoss?'midBoss':e.bossType);}else runGold+=e.elite?3:1;}
 function draw(now){const ctx=r.ctx;for(const event of events){if(!r.isNearScreen(event.x,event.y))continue;const x=r.worldToScreenX(event.x),y=r.worldToScreenY(event.y);ctx.save();ctx.fillStyle='#fff5cd';ctx.strokeStyle='#daa856';ctx.lineWidth=3;ctx.beginPath();ctx.arc(x,y,event.r,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.font='26px Segoe UI Emoji';ctx.textAlign='center';ctx.fillText(MAP_EVENTS[event.type].icon,x,y+9);ctx.font='12px Jua';ctx.fillStyle='#fff';ctx.fillText(MAP_EVENTS[event.type].name,x,y+45);ctx.restore();}
  if(pet!=='fairy'){const pos=r.petPosition(now);ctx.save();ctx.font='24px Segoe UI Emoji';ctx.textAlign='center';ctx.fillText(PETS[pet].icon,r.worldToScreenX(pos.x),r.worldToScreenY(pos.y)-18);ctx.restore();}
  if(NEW_CHARACTERS[s.character]){ctx.save();ctx.font='23px Segoe UI Emoji';ctx.textAlign='center';ctx.fillText(NEW_CHARACTERS[s.character].icon,r.worldToScreenX(p.x),r.worldToScreenY(p.y)-45);ctx.restore();}}
 return {start,tick,draw,closeShop,purchase,get goods(){return goods;},drawCharacter(now){return !!NEW_CHARACTERS[s.character]&&drawAnimation(r.ctx,s.character+'-walk',r.worldToScreenX(p.x),r.worldToScreenY(p.y),70,now,{direction:p.facing||0,moving:now<(p.movingUntil||0),reduced:r.v2.settings.reduced});},skill,petTick,preventDeath,killed,interact,spawnEvent,midBoss,get events(){return events;},get runGold(){return runGold;},get pet(){return pet;},get cleared(){return cleared;}};
}
