import {seeded} from '../math-engine.js';
export function roomLayout(seed,room){const random=seeded((seed+room*7919)>>>0),walls=[];for(let i=0;i<6;i++){const x=90+Math.floor(random()*4)*200,y=90+Math.floor(random()*3)*190;if(Math.hypot(x+55-500,y+35-360)<170)continue;if(!walls.some(w=>Math.abs(w.x-x)<130&&Math.abs(w.y-y)<100))walls.push({x,y,w:110+Math.floor(random()*50),h:65});}return {width:1000,height:720,walls,theme:room%3};}
export function constrainCircle(p,walls,width,height){const radius=p.r||14;p.x=Math.max(radius,Math.min(width-radius,p.x));p.y=Math.max(radius,Math.min(height-radius,p.y));for(const w of walls){const nx=Math.max(w.x,Math.min(w.x+w.w,p.x)),ny=Math.max(w.y,Math.min(w.y+w.h,p.y)),dx=p.x-nx,dy=p.y-ny,d=Math.hypot(dx,dy);if(d>=radius)continue;if(d>0){p.x=nx+dx/d*radius;p.y=ny+dy/d*radius;}else{const edges=[{d:p.x-w.x,x:w.x-radius,y:p.y},{d:w.x+w.w-p.x,x:w.x+w.w+radius,y:p.y},{d:p.y-w.y,x:p.x,y:w.y-radius},{d:w.y+w.h-p.y,x:p.x,y:w.y+w.h+radius}].sort((a,b)=>a.d-b.d);p.x=edges[0].x;p.y=edges[0].y;}}return p;}
export function createDungeon(r){let active=false,layout=null,seed=0,room=0;
 function enter(number){room=number;layout=roomLayout(seed,number);r.state.dungeonRooms=number;r.state.map={...r.MAPS.library,name:'수학 던전 '+number+'번째 방',worldW:layout.width,worldH:layout.height,base:['#183f43','#352e50','#34492e'][layout.theme]};r.state.worldW=layout.width;r.state.worldH=layout.height;r.player.x=500;r.player.y=360;r.makeDecorations();r.decorations=r.decorations.filter(d=>!layout.walls.some(w=>d.x>w.x-25&&d.x<w.x+w.w+25&&d.y>w.y-25&&d.y<w.y+w.h+25));r.portals=[];r.projectiles=[];for(const event of r.v3.content.events)event.used=true;r.updateCamera();}
 function start(config){active=config.gameMode==='dungeon';seed=Date.now()>>>0;room=0;layout=null;if(active)enter(1);}
 function answer(){if(!active)return;const next=1+Math.floor(r.v2.answers.length/3);if(next>room&&r.v2.answers.length<r.v2.config.target){enter(next);r.state.mathEnergy=Math.min(100,r.state.mathEnergy+15);r.v3.content.spawnEvent('treasure');r.showToast('🚪 새로운 던전 방 '+room);}}
 function constrain(p,from){if(!active)return;if(!from){constrainCircle(p,layout.walls,layout.width,layout.height);return;}const dx=p.x-from.x,dy=p.y-from.y,steps=Math.max(1,Math.ceil(Math.hypot(dx,dy)/10));p.x=from.x;p.y=from.y;for(let i=0;i<steps;i++){p.x+=dx/steps;p.y+=dy/steps;constrainCircle(p,layout.walls,layout.width,layout.height);}}
 function draw(){if(!active)return;const ctx=r.ctx;for(const w of layout.walls){const x=r.worldToScreenX(w.x),y=r.worldToScreenY(w.y);ctx.fillStyle='#15282c';ctx.fillRect(x,y+7,w.w,w.h);ctx.fillStyle='#738c85';ctx.fillRect(x,y,w.w,w.h-6);ctx.strokeStyle='#b1c3a3';ctx.lineWidth=2;ctx.strokeRect(x+3,y+3,w.w-6,w.h-12);ctx.strokeStyle='#536b68';for(let dx=28;dx<w.w;dx+=28){ctx.beginPath();ctx.moveTo(x+dx,y);ctx.lineTo(x+dx,y+w.h-6);ctx.stroke();}}ctx.fillStyle='#fff4d7';ctx.font='16px Jua';ctx.textAlign='center';ctx.fillText('수학 던전 '+room+' · 3문항을 풀면 다음 방',r.worldToScreenX(500),r.worldToScreenY(35));}
 return {start,answer,constrain,draw,get active(){return active;},get layout(){return layout;},get room(){return room;}};
}
