export const PROGRESS_KEY='math-survival-3.progress.v1';
export const PERMANENT={health:{name:'튼튼한 체력',cost:40,max:5},might:{name:'공격력 훈련',cost:50,max:5},speed:{name:'이동 훈련',cost:45,max:5},regen:{name:'회복 훈련',cost:55,max:5},luck:{name:'행운 훈련',cost:60,max:5}};
const thresholds={kills:[5,25,100,250,500,1000,2500,5000],correct:[1,5,10,25,50,100],longest:[60,180,480,900,1200,1800],bosses:[1,3,6,12],runs:[1,5,10,20],evolutions:[1,3,6],worldCount:[3,6]};
const names={kills:'누적 몬스터',correct:'누적 정답',longest:'최고 생존(초)',bosses:'누적 보스',runs:'모험 기록',evolutions:'누적 진화',worldCount:'탐험한 월드'};
export const ACHIEVEMENTS=Object.entries(thresholds).flatMap(([stat,values])=>values.map((target,i)=>({id:`${stat}-${target}`,stat,target,name:`${names[stat]} ${target}`,reward:5+i*3})));
const empty=()=>({schemaVersion:1,audio:{master:1,music:.6,effects:.8},coins:0,totalGold:0,upgrades:{},characters:['explorer','mage','guardian'],pets:['fairy'],achievements:[],seen:{weapons:[],characters:[],pets:[],monsters:[],worlds:[]},stats:{runs:0,kills:0,correct:0,bosses:0,longest:0,evolutions:0,worldCount:0},settled:[],history:[]});
export function validateProgress(d){if(!d||d.schemaVersion!==1||!Number.isSafeInteger(d.coins)||d.coins<0||!Number.isSafeInteger(d.totalGold)||d.totalGold<0||!d.upgrades||!d.stats||!d.seen)throw Error('게임 성장 백업 형식 오류');for(const key of ['characters','pets','achievements','settled','history'])if(!Array.isArray(d[key]))throw Error('게임 성장 목록 형식 오류');for(const key of ['weapons','characters','pets','monsters','worlds'])if(!Array.isArray(d.seen[key])||!d.seen[key].every(x=>typeof x==='string'))throw Error('도감 형식 오류');if(d.characters.some(x=>typeof x!=='string')||d.pets.some(x=>typeof x!=='string')||d.settled.some(x=>typeof x!=='string')||d.achievements.some(x=>typeof x!=='string'))throw Error('해금 목록 형식 오류');for(const [id,level]of Object.entries(d.upgrades))if(!PERMANENT[id]||!Number.isInteger(level)||level<0||level>PERMANENT[id].max)throw Error('영구 강화 형식 오류');for(const stat of Object.values(d.stats))if(!Number.isFinite(stat)||stat<0)throw Error('통계 형식 오류');if(d.audio&&Object.values(d.audio).some(v=>!Number.isFinite(v)||v<0||v>1))throw Error('음량 형식 오류');return structuredClone(d);}
export function createProgress(storage){let data=empty(),error='',blocked=false;try{storage??=globalThis.localStorage;const raw=storage.getItem(PROGRESS_KEY);if(raw)data=validateProgress(JSON.parse(raw));}catch(e){error='게임 성장 기록을 읽지 못했습니다. 기존 원문을 보존합니다. '+e.message;blocked=true;}
 function save(){if(blocked)return false;try{storage.setItem(PROGRESS_KEY,JSON.stringify(data));error='';return true;}catch(e){error='게임 성장 저장 실패. 현재 판은 플레이할 수 있습니다. '+e.message;return false;}}
 function settle(run){if(data.settled.includes(run.id))return false;data.settled.push(run.id);data.stats.runs++;for(const key of ['kills','correct','bosses','evolutions'])data.stats[key]=(data.stats[key]||0)+(run[key]||0);data.stats.longest=Math.max(data.stats.longest,run.seconds||0);const gold=Math.max(0,Math.floor(run.gold||0));data.coins+=gold;data.totalGold+=gold;
 for(const [key,ids]of Object.entries(run.seen||{}))if(data.seen[key])data.seen[key]=[...new Set([...data.seen[key],...ids])];data.stats.worldCount=data.seen.worlds.length;
 for(const a of ACHIEVEMENTS)if(!data.achievements.includes(a.id)&&data.stats[a.stat]>=a.target){data.achievements.push(a.id);data.coins+=a.reward;data.totalGold+=a.reward;}
 data.history.push({...run,date:run.date||new Date().toISOString()});save();return true;}
 function upgrade(id){const spec=PERMANENT[id],level=data.upgrades[id]||0;if(!spec||level>=spec.max||data.coins<spec.cost*(level+1)||blocked)return false;data.coins-=spec.cost*(level+1);data.upgrades[id]=level+1;save();return true;}
 function unlock(kind,id,cost,condition=true){if(!['characters','pets'].includes(kind)||data[kind].includes(id)||!condition||data.coins<cost||blocked)return false;data.coins-=cost;data[kind].push(id);save();return true;}
 function restore(raw){if(typeof raw!=='string'||raw.length>5*1024*1024)throw Error('백업은 5 MiB 이하입니다.');const next=validateProgress(JSON.parse(raw));data=next;blocked=false;return save();}
 return {get data(){return data;},get error(){return error;},get blocked(){return blocked;},save,settle,upgrade,unlock,restore};
}
export function dailySeed(date=new Date()){const day=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Seoul',year:'numeric',month:'2-digit',day:'2-digit'}).format(date);let seed=2166136261;for(const c of day)seed=Math.imul(seed^c.charCodeAt(0),16777619)>>>0;return {day,seed};}
