import {NEW_CHARACTERS,PETS,BOSSES} from './content-data.js';
import {MONSTERS} from './monsters.js';
import {NEW_WEAPONS,LEGACY_WEAPONS,PASSIVES,EVOLUTIONS,ULTIMATES} from './weapons-data.js';
import {PERMANENT,ACHIEVEMENTS,dailySeed} from './progress.js';
const $=id=>document.getElementById(id),esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export function createProgressUI(r,store){let lastHUD=0;
 function render(){const d=store.data;$('gameGold').textContent=String(d.coins);$('growthError').textContent=store.error;$('bestSurvival').textContent=Math.floor(d.stats.longest)+'초';
  $('permanentList').innerHTML=Object.entries(PERMANENT).map(([id,s])=>{const level=d.upgrades[id]||0,cost=s.cost*(level+1);return `<button data-upgrade="${id}" ${store.blocked||level>=s.max||d.coins<cost?'disabled':''}>${s.name} ${level}/${s.max}<br>${level>=s.max?'최대 강화':cost+'골드'}</button>`;}).join('');
  $('unlockList').innerHTML=[...Object.entries(NEW_CHARACTERS).map(([id,c])=>({id,kind:'characters',name:c.name,cost:c.unlock,owned:d.characters.includes(id),condition:d.stats.runs>=1,conditionText:'모험 1회'})),...Object.entries(PETS).filter(([id])=>id!=='fairy').map(([id,c])=>({id,kind:'pets',name:c.name,cost:c.unlock,owned:d.pets.includes(id),condition:d.stats.correct>=1,conditionText:'정답 1회'}))].map(c=>`<button data-unlock="${c.id}" data-kind="${c.kind}" data-cost="${c.cost}" ${store.blocked||c.owned||!c.condition||d.coins<c.cost?'disabled':''}>${c.name}<br>${c.owned?'해금 완료':c.cost+'골드 · '+c.conditionText}</button>`).join('');
  for(const [id,owned]of [['character',d.characters],['petSelect',d.pets]])for(const option of $(id).options){option.disabled=!owned.includes(option.value);option.textContent=option.textContent.replace(' 🔒','')+(option.disabled?' 🔒':'');}for(const id of ['character','petSelect'])if($(id).selectedOptions[0]?.disabled)$(id).value=id==='character'?'explorer':'fairy';
  $('achievementList').innerHTML=ACHIEVEMENTS.map(a=>`<li>${d.achievements.includes(a.id)?'✅':'🔒'} ${a.name} · ${Math.min(a.target,Math.floor(d.stats[a.stat]||0))}/${a.target}</li>`).join('');
  const catalog={weapons:{...LEGACY_WEAPONS,...NEW_WEAPONS},characters:{explorer:{name:'용감한 탐험가'},mage:{name:'번개 마법사'},guardian:{name:'수학 수호자'},...NEW_CHARACTERS},pets:PETS,monsters:MONSTERS};
  $('encyclopedia').innerHTML=Object.entries(catalog).map(([kind,items])=>`<section><h3>${({weapons:'무기',characters:'캐릭터',pets:'펫',monsters:'몬스터'})[kind]}</h3><div class="catalogGrid">${Object.entries(items).map(([id,item])=>`<div class="catalogEntry">${item.icon||'✦'} ${item.name}<small>${d.seen[kind].includes(id)?'발견한 기록 있음':'아직 발견하지 않음'}</small></div>`).join('')}</div></section>`).join('');
  $('evolutionBook').innerHTML='<h3>진화 상자 조합</h3>'+EVOLUTIONS.map(e=>`<p>${({...LEGACY_WEAPONS,...NEW_WEAPONS})[e.weapon].name} Lv.${e.weaponLevel} + ${PASSIVES[e.passive].name} Lv.${e.passiveLevel} → 상자를 먹으면 진화</p>`).join('')+'<h3>합체 궁극기</h3>'+ULTIMATES.map(u=>`<p>${u.name}: ${u.weapons.map(id=>({...LEGACY_WEAPONS,...NEW_WEAPONS})[id].name+' 진화').join(' + ')} · 수학 에너지 20 · 자동 발동</p>`).join('');
  $('gameHistory').innerHTML=d.history.slice(-20).reverse().map(x=>`<p>${esc(x.date?.slice(0,10)||'')} · ${esc(x.mode)} · ${Math.floor(x.seconds)}초 · ${x.gold}골드 · ${esc(x.outcome)}</p>`).join('')||'<p>아직 게임 기록이 없습니다.</p>';
  $('dailyInfo').textContent='오늘의 도전 · '+dailySeed().day+' · 8분 생존';
 }
 function mount(){const section=document.createElement('section');section.id='v3Home';section.innerHTML=`<div class="adventureBanner"><span>3.0 모험 준비</span><p>🌱 숲에서 시작해 나만의 무기 조합을 완성해요</p><div>🪙 골드 <strong id="gameGold">0</strong> · 🏆 최고 생존 <strong id="bestSurvival">0초</strong></div><p id="dailyInfo"></p></div><p id="growthError" role="status"></p><details><summary>🌟 영구 성장·캐릭터·펫 해금</summary><p>학습 기록과 별도로 이 브라우저에 저장합니다. 골드는 이번 판의 처치·보스 보상과 업적으로 얻습니다.</p><div id="permanentList" class="catalogGrid"></div><h3>새 친구 해금</h3><div id="unlockList" class="catalogGrid"></div></details><details><summary>📚 도감·진화 조합·업적</summary><div id="encyclopedia"></div><div id="evolutionBook"></div><ul id="achievementList"></ul></details><details><summary>🗃️ 게임 기록·성장 백업</summary><div class="row"><button id="gameBackup">게임 성장 JSON 저장</button><label>게임 성장 복원<input id="gameRestore" type="file" accept="application/json,.json"></label></div><p id="gameRestorePreview" role="status"></p><button id="gameRestoreApply" hidden>확인한 게임 성장 백업으로 복원</button><div id="gameHistory"></div></details><details><summary>🎵 음악·효과음 음량</summary><div class="setupGrid"><label>전체 음량<input id="masterVolume" type="range" min="0" max="1" step="0.05"></label><label>배경 음악<input id="musicVolume" type="range" min="0" max="1" step="0.05"></label><label>효과음<input id="effectsVolume" type="range" min="0" max="1" step="0.05"></label></div></details>`;$('v2Setup').prepend(section);
  section.addEventListener('click',e=>{const upgrade=e.target.closest('[data-upgrade]'),unlock=e.target.closest('[data-unlock]');if(upgrade)store.upgrade(upgrade.dataset.upgrade);if(unlock){const kind=unlock.dataset.kind,condition=kind==='characters'?store.data.stats.runs>=1:store.data.stats.correct>=1;store.unlock(kind,unlock.dataset.unlock,Number(unlock.dataset.cost),condition);}if(upgrade||unlock){render();r.v2.validate();$('character').dispatchEvent(new Event('change',{bubbles:true}));}});
  $('gameBackup').addEventListener('click',()=>{const blob=new Blob([JSON.stringify(store.data,null,2)],{type:'application/json'}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='math-survival-game-growth.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),0);});let pending=null;
  $('gameRestore').addEventListener('change',async e=>{pending=null;$('gameRestoreApply').hidden=true;try{const file=e.target.files[0];if(!file||file.size>5*1024*1024)throw Error('5 MiB 이하 게임 성장 JSON을 선택하세요.');const raw=await file.text(),{validateProgress}=await import('./progress.js'),next=validateProgress(JSON.parse(raw));pending=raw;$('gameRestorePreview').textContent=`미리보기: 골드 ${next.coins}, 모험 ${next.stats.runs}회. 적용하면 게임 성장만 교체하며 학습 기록은 유지합니다.`;$('gameRestoreApply').hidden=false;}catch(err){$('gameRestorePreview').textContent=err.message;}});
  $('gameRestoreApply').addEventListener('click',()=>{if(!pending)return;store.restore(pending);pending=null;$('gameRestoreApply').hidden=true;render();});
  for(const [key,id]of Object.entries({master:'masterVolume',music:'musicVolume',effects:'effectsVolume'})){$(id).value=store.data.audio?.[key]??({master:1,music:.6,effects:.8})[key];$(id).addEventListener('input',()=>{store.data.audio??={master:1,music:.6,effects:.8};store.data.audio[key]=Number($(id).value);store.save();applyAudio();});}
  $('gameHeader').insertAdjacentHTML('beforeend','<div id="v3HUD"><span id="energyHUD">🔋 수학 에너지 0/100</span><span id="waveHUD">🌊 웨이브 1</span><span id="slotsHUD">무기 0/6 · 패시브 0/6</span></div>');render();
 }
 function set(id,text){if($(id).textContent!==text)$(id).textContent=text;}function hud(now){if(now-lastHUD<200)return;lastHUD=now;set('energyHUD','🔋 수학 에너지 '+Math.floor(r.state.mathEnergy||0)+'/100');set('waveHUD',r.v3.modes.variant==='defense'?'🏰 방어 '+r.v3.modes.wave+'/20':'🌊 웨이브 '+r.v3.battle.wave+' · 🪙 '+r.v3.content.runGold);set('slotsHUD','무기 '+Object.keys(r.v3.weapons.levels).length+'/6 · 패시브 '+Object.keys(r.v3.weapons.passives).length+'/6');}
 function applyAudio(){if(!r.audioReady)return;const audio=store.data.audio||{master:1,music:.6,effects:.8};r.masterGain.gain.value=r.muted?0:audio.master;r.musicGain.gain.value=.12*audio.music;r.sfxGain.gain.value=.22*audio.effects;}return {mount,render,hud,applyAudio,reset(){lastHUD=-Infinity;}};
}
