import {validateConfig} from '../configuration.js';
import {validRecord} from '../storage.js';
export function assignmentURL(config, curriculum, base) {
 const task={grade:config.grade,domain:config.domain,unit:config.unit,level:config.level,auto:!!config.auto,target:config.target,limit:config.limit,combat:config.combat,questionMode:config.questionMode||'orbs'};
 const errors=validateConfig({...task,mode:'explore',character:'explorer',weapon:'storm'},curriculum);if(errors.length)throw Error(errors.join(' '));
 const url=new URL(base);url.search='';url.hash='';url.searchParams.set('task',JSON.stringify({version:1,...task}));return url.href;
}
export function readAssignment(url,curriculum){const raw=new URL(url).searchParams.get('task');if(!raw)return null;if(raw.length>3000)throw Error('과제 링크가 너무 깁니다.');const task=JSON.parse(raw);if(task.version!==1)throw Error('지원하지 않는 과제 링크입니다.');const safe={};for(const key of ['grade','domain','unit','level','auto','target','limit','combat','questionMode'])safe[key]=task[key];assignmentURL(safe,curriculum,url);if(typeof safe.auto!=='boolean'||!['orbs','popup'].includes(safe.questionMode))throw Error('과제 설정 형식 오류');return safe;}
export function mergeResults(files){const ids=new Set(),records=[],rejected=[];let duplicates=0;
 for(const file of files){try{if(new TextEncoder().encode(file.text).length>10*1024*1024)throw Error('10 MiB 초과');const data=JSON.parse(file.text),rows=Array.isArray(data.records)?data.records:[data];for(const row of rows){if(!validRecord(row))throw Error('학습 결과 schemaVersion 2 형식 오류');}for(const row of rows){if(ids.has(row.sessionId)){duplicates++;continue;}ids.add(row.sessionId);records.push(row);}}catch(e){rejected.push({file:file.name,error:e.message});}}
 const concepts={},units={};let total=0,correct=0;
 for(const r of records)for(const a of r.answers){total++;correct+=Number(a.correct);for(const [table,key]of [[units,a.unit],[concepts,a.unit+' / '+(a.type||a.typeId||'유형 미기록')]]){const item=table[key]??={total:0,correct:0,wrong:0,hints:0,review:0};item.total++;item.correct+=Number(a.correct);item.wrong+=Number(!a.correct);item.hints+=Number(!!a.hintUsed);item.review+=Number(!!a.review);}}
 return {records,rejected,duplicates,total,correct,accuracy:total?Math.round(100*correct/total):null,units,concepts};
}
export function classCSV(report){const cell=x=>'"'+String(x).replaceAll('"','""')+'"';return '\uFEFF'+[['개념','응답','정답','오답','힌트','복습'],...Object.entries(report.concepts).map(([key,v])=>[/^[=+\-@]/.test(key)?"'"+key:key,v.total,v.correct,v.wrong,v.hints,v.review])].map(row=>row.map(cell).join(',')).join('\r\n');}
export function mountTeacher(r,curriculum,configFromUI){const $=id=>document.getElementById(id),root=document.createElement('details');root.id='teacherTools';root.innerHTML='<summary>🏫 교사용 과제 공유·학급 결과 합치기</summary><p>수학 탐험의 학년·단원·난이도·목표·시간을 링크로 공유합니다. 실명을 입력하지 않습니다. 결과 파일은 이 브라우저에서만 처리하며 실시간 모니터링·자동 동기화는 제공하지 않습니다.</p><button id="createTask">현재 수학 설정으로 과제 링크 만들기</button><label>공유할 링크<textarea id="taskURL" readonly rows="3"></textarea></label><p id="taskStatus" role="status"></p><label>여러 학생의 결과 JSON 또는 전체 학습 백업 JSON<input id="classFiles" type="file" multiple accept=".json,application/json"></label><p>CSV는 결과 내보내기에 사용합니다. 파일 합치기는 문항별 원본 데이터가 있는 JSON으로 진행합니다. 같은 세션은 한 번만 집계합니다.</p><div id="classReport" role="status"></div><button id="classExport" disabled>학급 개념 통계 CSV</button><button id="classClear">불러온 학급 결과 비우기</button>';$('v2Setup').append(root);let report=null;
 $('createTask').onclick=()=>{try{$('taskURL').value=assignmentURL(configFromUI(),curriculum,location.href);$('taskStatus').textContent='링크를 복사해 공유하세요. 접속한 학생은 시작 버튼을 눌러 플레이합니다.';}catch(e){$('taskStatus').textContent=e.message;}};
 $('classFiles').onchange=async e=>{if(e.target.files.length>50){$('classReport').textContent='한 번에 50개 이하 파일을 선택하세요.';return;}const files=[];for(const f of e.target.files)files.push({name:f.name,text:f.size>10*1024*1024?'':await f.text()});report=mergeResults(files);$('classReport').replaceChildren();const p=document.createElement('p');p.textContent=`기록 ${report.records.length}개 · 중복 ${report.duplicates}개 · 제외 파일 ${report.rejected.length}개 · 정답 ${report.correct}/${report.total} · ${report.accuracy??'응답 없음'}${report.accuracy===null?'':'%'}`;$('classReport').append(p);for(const [key,item]of Object.entries(report.concepts)){const line=document.createElement('p');line.textContent=key+' · 오답 '+item.wrong+'/'+item.total+' · 힌트 '+item.hints+' · 복습 '+item.review;$('classReport').append(line);}for(const item of report.rejected){const line=document.createElement('p');line.textContent=item.file+': '+item.error;$('classReport').append(line);}$('classExport').disabled=!report.records.length;};
 $('classExport').onclick=()=>{if(!report)return;const url=URL.createObjectURL(new Blob([classCSV(report)],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download='math-survival-class-concepts.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('classClear').onclick=()=>{report=null;$('classFiles').value='';$('classReport').replaceChildren();$('classExport').disabled=true;};
 try{const task=readAssignment(location.href,curriculum);if(task){$('mode').value='explore';for(const key of ['grade','domain']){$(key).value=task[key];$(key).dispatchEvent(new Event('change',{bubbles:true}));}$('unit').value=task.unit;$('unit').dispatchEvent(new Event('change',{bubbles:true}));for(const [key,id]of Object.entries({level:'mathLevel',target:'target',limit:'limit',combat:'difficulty',questionMode:'questionMode'}))$(id).value=task[key];$('autoLevel').checked=task.auto;$('mode').dispatchEvent(new Event('change',{bubbles:true}));$('taskStatus').textContent='공유 과제를 적용했습니다. 설정을 확인하고 시작하세요.';r.v2.validate();}}catch(e){$('taskStatus').textContent='과제 링크를 적용하지 않았습니다. '+e.message;}
}
