const fs=require('node:fs'),assert=require('node:assert/strict');
let pw;try{pw=require('playwright');}catch{pw=require('C:/Users/user/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');}
const checks=[],errors=[];
async function check(name,fn){try{await fn();checks.push({name,passed:true});console.log('PASS',name);}catch(e){checks.push({name,passed:false,error:e.message});console.log('FAIL',name,e.message);}}
(async()=>{
 const browser=await pw.chromium.launch({headless:true,channel:process.env.BROWSER_CHANNEL||'msedge'}),context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true}),page=await context.newPage();
 page.on('pageerror',e=>errors.push(e.message));page.on('response',r=>{if(r.status()>=400&&!r.url().includes('favicon'))errors.push(r.status()+' '+r.url());});
 await page.addInitScript(()=>{window.__instrument={intervals:0,listeners:{}};const interval=window.setInterval;window.setInterval=function(...args){__instrument.intervals++;return interval.apply(this,args);};const listener=window.addEventListener;window.addEventListener=function(type,...args){__instrument.listeners[type]=(__instrument.listeners[type]||0)+1;return listener.call(this,type,...args);};});
 await page.goto('http://127.0.0.1:4173/Math-Survival-2/?qa=1');await page.waitForFunction(()=>!!window.__game);
 await check('Pages 하위 경로 모듈·JSON 로딩',async()=>{assert(await page.locator('#grade').isVisible());assert.equal(await page.locator('#unit option').count(),6);});
 await page.screenshot({path:'docs/desktop-menu.png'});await page.click('#startBtn');
 await check('키보드 이동·대시·특수 스킬',async()=>{const before=await page.evaluate(()=>{__game.portals=[];return __game.player.x;});await page.keyboard.down('d');await page.waitForTimeout(180);await page.keyboard.press('Space');await page.keyboard.up('d');await page.waitForFunction(()=>__game.player.dashCooldown>0,{},{timeout:1000});await page.keyboard.press('e');assert(await page.evaluate(x=>__game.player.x>x&&__game.player.dashCooldown>0&&__game.state.skillReady>0,before));});
 await check('원본 전투·아이템·펫·경험치·레벨업 회귀',async()=>{assert(await page.evaluate(()=>{const r=__game;r.state.paused=false;r.enemies=[];r.spawnEnemy();r.clock=3000;r.shoot(r.clock);r.updatePet(r.clock);const pet=r.projectiles.find(p=>p.kind==='pet');const x=pet?.x;r.update(1000/60,r.clock);const moved=pet&&pet.x!==x;r.state.shield=0;r.player.invincible=0;r.enemies=[{x:r.player.x,y:r.player.y,r:20,hp:100,maxHp:100,speed:0,damage:8,wobble:0}];const hp=r.state.hp;r.update(1000/60,r.clock);const collision=r.state.hp<hp;r.applyItem({type:'shield'},r.clock);r.spawnExpDrops(r.player.x,r.player.y,10);const xp=r.state.exp;r.collectExpDrop(r.expDrops[0]);const experience=r.state.exp>xp;r.state.exp=r.expNeed();r.checkLevelUp();const level=r.state.levelUpPending&&r.state.level===2;r.chooseUpgrade(r.upgradeOptions()[0]);return moved&&collision&&experience&&level&&r.state.shield>0&&!r.state.paused;}));});
 await check('정답·오답·콤보·해설·취약 재출제',async()=>{assert(await page.evaluate(()=>{const r=__game;r.spawnQuiz();r.resolveAnswer(r.answerOrbs.find(o=>o.correct));const correct=r.state.correct===1&&r.state.combo===1;r.spawnQuiz();const weak=r.state.problem.id;r.resolveAnswer(r.answerOrbs.find(o=>!o.correct));let replay=false;for(let i=0;i<7;i++)if(r.v2.makeProblem().id===weak)replay=true;return correct&&r.state.wrong===1&&replay&&document.querySelector('#explanation').textContent.includes('정답');}));});
 await check('신규 무기 4종 강화·진화·공격',async()=>{assert(await page.evaluate(()=>{const r=__game;r.state.bestCombo=5;for(const opt of r.v2.upgrades())opt.apply();for(let i=0;i<3;i++)for(const opt of r.v2.upgrades())opt.apply();r.enemies=[];r.spawnEnemy();const e=r.enemies[0];e.hp=e.maxHp=1000;r.clock+=20000;r.v2.combat.tick(r.clock);return Object.values(r.state.newWeapons).every(l=>l===3)&&Object.keys(r.state.evolved).length===4&&r.projectiles.some(p=>p.kind==='boomerang')&&e.hp<1000&&r.state.shield>0;}));});
 await check('보스 3종 × 2패턴·예고·충돌·보상',async()=>{assert(await page.evaluate(()=>{const r=__game;for(const key of ['forest','desert','library']){r.enemies=[];r.state.currentMapKey=key;r.state.map=r.MAPS[key];r.spawnBoss();const boss=r.enemies[0];boss.x=r.player.x+200;boss.y=r.player.y;r.clock+=4000;r.v2.combat.tick(r.clock);const first=boss.patternIndex;r.clock+=4000;r.v2.combat.tick(r.clock);if(first!==1||boss.patternIndex!==2)return false;}const h=r.v2.combat.hazards().at(-1);r.player.x=h.x+(h.shape==='ring'?h.r:0);r.player.y=h.y;r.player.invincible=0;r.state.shield=0;const hp=r.state.hp;r.clock=h.fireAt;r.v2.combat.tick(r.clock);if(r.state.hp>=hp)return false;const boss=r.enemies[0];boss.hp=0;r.state.paused=false;r.update(1000/60,r.clock);return r.state.kills>0&&r.items.some(i=>i.type==='gem')&&r.expDrops.length>0;}));});
 await check('일시정지 동안 시간·버프·공격·위치 고정',async()=>{await page.evaluate(()=>{__game.state.levelUpQueue=0;__game.state.levelUpPending=false;__game.state.paused=false;__game.state.freezeUntil=__game.clock+2000;});await page.click('#pauseBtn');await page.waitForTimeout(70);const a=await page.evaluate(()=>JSON.stringify({state:__game.state,player:__game.player,enemies:__game.enemies,projectiles:__game.projectiles,clock:__game.clock}));await page.waitForTimeout(350);const b=await page.evaluate(()=>JSON.stringify({state:__game.state,player:__game.player,enemies:__game.enemies,projectiles:__game.projectiles,clock:__game.clock}));assert.equal(a,b);await page.click('#pauseBtn');});
 await check('게임 종료·학습 저장·JSON/CSV 내보내기',async()=>{if(!await page.locator('#playMenu').isVisible())await page.keyboard.press('Escape');await page.click('#quitGameBtn');assert(await page.locator('#learningReport').isVisible());assert(await page.evaluate(()=>JSON.parse(localStorage.getItem('math-survival-2.records.v1')).length===1));for(const id of ['exportJSON','exportCSV']){const download=page.waitForEvent('download');await page.click('#'+id);const d=await download;await d.saveAs('docs/'+d.suggestedFilename());assert((await d.suggestedFilename()).endsWith(id==='exportJSON'?'.json':'.csv'));}await page.screenshot({path:'docs/desktop-results.png'});});
 await check('10회 재시작·배열/스킬/학습 기록 초기화',async()=>{assert(await page.evaluate(()=>{const r=__game;for(let i=0;i<10;i++){r.resetGame();if(r.state.level!==1||r.state.correct||r.state.kills||r.state.skillReady||r.v2.answers.length||r.enemies.length)return false;r.state.score=100;r.state.correct=4;r.state.skillReady=99999;}r.resetGame();return r.state.score===0&&r.answerOrbs.length===4;}));});
 await check('타이머·키보드 이벤트·게임 루프 중복 방지',async()=>{assert(await page.evaluate(()=>__instrument.intervals===1&&__instrument.listeners.keydown===2&&__instrument.listeners.keyup===1&&__instrument.listeners.resize===1));const before=await page.evaluate(()=>__game.state.time);await page.waitForTimeout(400);const delta=await page.evaluate(t=>__game.state.time-t,before);assert(delta>.25&&delta<.65,String(delta));});
 await check('페이지 새로고침 뒤 학습 저장 유지',async()=>{await page.reload();await page.waitForFunction(()=>!!window.__game);assert((await page.locator('#historySummary').innerText()).includes('1회'));});
 await check('교사 설정·학년/영역/단원·탐험 목표 달성',async()=>{await page.selectOption('#mode','explore');await page.selectOption('#grade','6');await page.selectOption('#domain','number');await page.selectOption('#unit','g6-fracdiv');await page.fill('#target','2');await page.fill('#limit','30');await page.click('#startBtn');assert(await page.evaluate(()=>__game.state.problem.unit==='g6-fracdiv'&&__game.state.winTime===30));for(let i=0;i<2;i++){await page.evaluate(()=>{__game.state.paused=false;__game.state.levelUpPending=false;__game.spawnQuiz();});const idx=await page.evaluate(()=>__game.answerOrbs.findIndex(o=>o.correct));await page.click(`#answerAccess button[data-index="${idx}"]`);}await page.waitForFunction(()=>!__game.state.running);assert(await page.evaluate(()=>__game.v2.result.outcome==='complete'&&__game.state.correct===2));});
 await check('탐험 제한 시간 종료',async()=>{assert(await page.evaluate(()=>{__game.resetGame();__game.state.time=30;__game.update(16,__game.clock);return !__game.state.running&&__game.v2.result.outcome==='time-limit';}));});
 await check('캐릭터 3종 능력치·스킬 및 전투/수학 난이도 분리',async()=>{await page.click('#toStartBtn');const stats=[];for(const char of ['explorer','mage','guardian']){await page.selectOption('#character',char);await page.selectOption('#difficulty','hard');await page.selectOption('#mathLevel','1');await page.uncheck('#autoLevel');await page.click('#startBtn');stats.push(await page.evaluate(()=>({hp:__game.state.maxHp,rate:__game.state.fireRate,speed:__game.player.speed,level:__game.state.problem.level,combat:__game.state.difficulty})));await page.evaluate(()=>{__game.v2.combat.skill();});assert(await page.evaluate(()=>__game.state.skillReady>0));if(!await page.locator('#playMenu').isVisible())await page.keyboard.press('Escape');await page.click('#mainMenuBtn');}assert.equal(new Set(stats.map(s=>s.hp)).size,3);assert(stats.every(s=>s.level===1&&s.combat==='hard'));});
 await check('보스 챌린지 3연전 완료',async()=>{await page.selectOption('#mode','boss');await page.selectOption('#mapSelect','forest');await page.click('#startBtn');assert(await page.evaluate(()=>{const r=__game;for(let i=0;i<3;i++){const boss=r.enemies.find(e=>e.boss);if(!boss)return false;boss.hp=0;r.state.paused=false;r.state.levelUpPending=false;r.update(16,r.clock);r.v2.tick(16,r.clock);}return !r.state.running&&r.state.bossKills===3&&r.v2.result.outcome==='complete';}));});
 await check('서바이벌 생존 완료 및 체력 소진 종료',async()=>{await page.click('#toStartBtn');await page.selectOption('#mode','survival');await page.click('#startBtn');assert(await page.evaluate(()=>{const r=__game;r.state.time=180;r.update(16,r.clock);if(r.state.running||r.v2.result.outcome!=='complete')return false;r.resetGame();r.state.hp=0;r.update(16,r.clock);return !r.state.running&&r.v2.result.outcome==='defeat';}));});
 await page.click('#toStartBtn');await page.selectOption('#mode','survival');await page.click('#startBtn');await page.waitForTimeout(300);await page.screenshot({path:'docs/desktop-play.png'});
 await check('화면 크기 변경·경계에서 구슬 중복 방지',async()=>{await page.setViewportSize({width:760,height:1024});await page.waitForTimeout(50);assert(await page.evaluate(()=>{const r=__game;for(const [x,y] of [[20,20],[r.state.worldW-20,r.state.worldH-20]]){r.player.x=x;r.player.y=y;r.spawnQuiz();if(new Set(r.answerOrbs.map(o=>o.x+':'+o.y)).size!==4)return false;}return r.canvas.height===820;}));});
 const mobile=await browser.newContext({viewport:{width:390,height:844},hasTouch:true,isMobile:true,deviceScaleFactor:1}),mp=await mobile.newPage();mp.on('pageerror',e=>errors.push(e.message));await mp.goto('http://127.0.0.1:4173/Math-Survival-2/?qa=1');await mp.waitForFunction(()=>!!window.__game);await mp.screenshot({path:'docs/mobile-menu.png'});await mp.click('#startBtn');
 await check('모바일 실제 터치 조이스틱 이동·취소·대시·스킬',async()=>{const client=await mobile.newCDPSession(mp);const box=await mp.locator('#joystickZone').boundingBox(),x=box.x+box.width/2,y=box.y+box.height/2;const before=await mp.evaluate(()=>__game.player.x);await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await client.send('Input.dispatchTouchEvent',{type:'touchMove',touchPoints:[{x:x+35,y}]});await mp.waitForTimeout(220);await client.send('Input.dispatchTouchEvent',{type:'touchEnd',touchPoints:[]});assert(await mp.evaluate(b=>__game.player.x>b&&__game.joystickDelta.x===0,before));await mp.locator('#dashBtn').tap();await mp.waitForFunction(()=>__game.player.dashCooldown>0,{},{timeout:1000});await mp.locator('#skillBtn').tap();assert(await mp.evaluate(()=>__game.state.skillReady>0));await client.send('Input.dispatchTouchEvent',{type:'touchStart',touchPoints:[{x,y}]});await client.send('Input.dispatchTouchEvent',{type:'touchCancel',touchPoints:[]});assert(await mp.evaluate(()=>!__game.isJoystickActive&&__game.keys[' ']===false));});
 await check('모바일 핵심 HUD·문제·버튼 경계/겹침',async()=>{const boxes=await mp.evaluate(()=>['hud','playControls','questionBox','answerAccess','joystickZone','dashBtn'].map(id=>{const b=document.getElementById(id).getBoundingClientRect();return {id,x:b.x,y:b.y,w:b.width,h:b.height};}));for(const b of boxes){assert(b.x>=-1&&b.y>=-1&&b.x+b.w<=391&&b.y+b.h<=845,JSON.stringify(b));}for(let i=0;i<boxes.length;i++)for(let j=i+1;j<boxes.length;j++){const a=boxes[i],b=boxes[j];assert(!(a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y),a.id+' overlaps '+b.id);}});
 await mp.screenshot({path:'docs/mobile-play.png'});
 await check('모바일 가로 모드',async()=>{await mp.setViewportSize({width:844,height:390});await mp.screenshot({path:'docs/mobile-landscape.png'});assert(await mp.locator('#pauseBtn').isVisible());assert(await mp.evaluate(()=>__game.answerOrbs.length===4));});
 await check('소리·애니메이션 감소·저사양·글자 크기',async()=>{await mp.click('#mainMenuBtn');await mp.locator('.preferences summary').click();await mp.check('#reducedMotion');await mp.check('#lowPower');await mp.selectOption('#fontSize','1.3');await mp.click('#muteBtn');await mp.click('#startBtn');assert(await mp.evaluate(()=>__game.v2.settings.reduced&&__game.v2.settings.low&&__game.v2.settings.font===1.3&&__game.decorations.length===45&&__game.audioReady&&__game.muted));});
 await browser.close();fs.writeFileSync('docs/browser-results.json',JSON.stringify({date:new Date().toISOString(),browser:'Microsoft Edge / Playwright',checks,errors,limitations:['터치 검사는 브라우저 입력 이벤트이며 실제 모바일 기기 검사 아님','오디오는 초기화·음소거 상태 검사이며 청취 검사 아님','실제 GitHub Pages 배포는 승인 대기']},null,2));if(errors.length||checks.some(c=>!c.passed)){console.log('ERRORS',errors);process.exitCode=1;}
})().catch(e=>{console.error(e);process.exitCode=1;});
