import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';
import {createStore,KEY,LEGACY,MAX_BACKUP_BYTES} from '../src/storage.js';import {createMastery} from '../src/mastery.js';import {generateProblem} from '../src/math-engine.js';import {validateConfig,validateCurriculum} from '../src/configuration.js';
const c=JSON.parse(fs.readFileSync(new URL('../data/curriculum.json',import.meta.url))),cfg={grade:2,domain:'number',unit:'g2-add',level:2,auto:true,mode:'explore',target:10,limit:180,character:'explorer',weapon:'storm'};
const memory=()=>{const values=new Map();return {values,getItem:k=>values.get(k)||null,setItem:(k,v)=>values.set(k,v),removeItem:k=>values.delete(k)};};
const answer=(id,unit='g2-add',extra={})=>({id,conceptId:id,text:'2 + 3 = ?',answer:'5',correct:true,unit,level:2,type:'add',operands:[2,3],date:new Date().toISOString(),...extra});
const record=id=>({sessionId:id,date:new Date().toISOString(),schemaVersion:2,config:cfg,answers:[answer(id)],outcome:'complete',accuracy:100});
test('정수 설정·빈 영역·지원 단계·손상 교육과정 검증',()=>{assert.deepEqual(validateConfig(cfg,c),[]);for(const target of [0,1.5,101,NaN])assert(validateConfig({...cfg,target},c).length);for(const limit of [0,30.5,1801,NaN])assert(validateConfig({...cfg,limit},c).length);assert(validateConfig({...cfg,domain:'data'},c).length);assert(validateConfig({...cfg,grade:1,domain:'geometry',unit:'g1-shapes',level:2},c).length);assert.throws(()=>validateCurriculum({grades:[]}));assert(validateCurriculum(c));});
test('단원별 창 격리·중복·힌트·복습 제외·창 한번 소비',()=>{const m=createMastery();for(let i=0;i<5;i++){m.record(answer('a'+i),true);m.record(answer('b'+i,'g3-div',{level:4,correct:false}),true);}assert.equal(m.units['g2-add'].level,3);assert.equal(m.units['g3-div'].level,3);assert.equal(m.units['g2-add'].window.length,0);for(let i=0;i<5;i++)m.record(answer('a'+i),true);assert.equal(m.units['g2-add'].level,3);for(let i=0;i<5;i++)m.record(answer('h'+i,'g2-add',{hintUsed:true}),true);assert.equal(m.units['g2-add'].window.length,0);m.record(answer('review','g2-add',{review:true}),true);assert.equal(m.units['g2-add'].window.length,0);});
test('고정 단계·3/5 유지·경계 단계',()=>{const m=createMastery();for(let i=0;i<5;i++)m.record(answer('f'+i),false);assert.equal(m.level('g2-add',2,false),2);for(let i=0;i<5;i++)m.record(answer('v'+i,'g3-div',{correct:i<3}),true);assert.equal(m.units['g3-div'].level,2);for(let i=0;i<10;i++)m.record(answer('z'+i,'g2-sub',{level:1,correct:false}),true);assert.equal(m.units['g2-sub'].level,1);});
test('동형 복습 두 성공·힌트 및 동일 문항 제외·복습 해소 reload 유지',()=>{const m=createMastery();m.record(answer('bad','g2-add',{correct:false}),true);const rev=m.units['g2-add'].reviews.bad;for(const row of [answer('new1','g2-add',{review:true,reviewKey:'bad',hintUsed:true}),answer('new1','g2-add',{review:true,reviewKey:'bad'}),answer('new1','g2-add',{review:true,reviewKey:'bad'})])m.record(row,true);assert.equal(rev.successCount,1);m.record(answer('new2','g2-add',{review:true,reviewKey:'bad'}),true);assert(rev.resolved);const reloaded=createMastery(JSON.parse(JSON.stringify(m.units)));assert.equal(reloaded.due('g2-add'),undefined);reloaded.record(answer('bad','g2-add',{correct:false}),true);assert(reloaded.units['g2-add'].reviews.bad.resolved);});
test('v1 원본 백업·부분 손상 격리·알 수 없는 새 필드 추정 안함',()=>{const st=memory(),legacy=[{date:new Date().toISOString(),config:{grade:2},answers:[answer('old')],accuracy:100},null,{answers:'bad'}];st.setItem(LEGACY,JSON.stringify(legacy));const store=createStore(st);assert.equal(store.data.records.length,1);assert.equal(store.data.quarantine.length,2);assert.equal(st.getItem(LEGACY),st.getItem(LEGACY+'.backup'));assert.equal(store.data.records[0].answers[0].responseMs,undefined);assert.equal(store.data.records[0].answers[0].hintUsed,undefined);});
test('손상 JSON·차단 읽기·할당량 실패',()=>{const st=memory();st.setItem(LEGACY,'{bad');assert.equal(createStore(st).data.quarantine.length,1);const broken=memory();broken.setItem(KEY,'{bad');const db=createStore(broken);assert(db.error);assert.equal(broken.getItem(KEY),'{bad');assert(createStore({getItem(){throw Error('blocked');}}).error);const quota=createStore({getItem:()=>null,setItem(){throw Error('quota');}});assert.equal(quota.save(record('q'),{}),false);assert.equal(quota.data.records.length,1);});
test('100회 초과 보존·체크포인트 복구·동일 세션 멱등',()=>{const st=memory(),store=createStore(st);for(let i=0;i<130;i++)store.save(record('s'+i),{});assert.equal(createStore(st).data.records.length,130);store.checkpoint(record('recover'),{});const again=createStore(st);assert.equal(again.data.records.at(-1).outcome,'interrupted');assert.equal(createStore(st).data.records.length,131);again.save(record('recover'),{});assert.equal(again.data.records.length,131);});
test('백업 미리보기·중복·버전·크기·원자적 검증·삭제',()=>{const st=memory(),store=createStore(st);store.save(record('a'),{});const incoming={schemaVersion:2,records:[record('a'),record('b')],mastery:{}};const preview=store.preview(JSON.stringify(incoming));assert.equal(preview.added,1);assert.equal(preview.duplicates,1);assert.equal(store.data.records.length,1);store.restore(preview);assert.equal(store.data.records.length,2);assert.throws(()=>store.preview(JSON.stringify({...incoming,schemaVersion:3})));assert.throws(()=>store.preview(JSON.stringify({...incoming,records:[null]})));assert.throws(()=>store.preview(' '.repeat(MAX_BACKUP_BYTES+1)));store.remove(['a']);assert.equal(store.data.records.length,1);});
test('잘못된 응답 필드 격리·손상 v2 원본 백업·해소 복습 오래된 백업 복원 유지',()=>{const st=memory();st.setItem(KEY,'{bad');const damaged=createStore(st);damaged.save(record('new'),{});assert.equal(st.getItem(KEY+'.damaged-backup'),'{bad');const m=createMastery();m.record(answer('bad','g2-add',{correct:false}),true);const old=JSON.parse(JSON.stringify(m.units));for(const key of ['fresh1','fresh2'])m.record(answer(key,'g2-add',{review:true,reviewKey:'bad'}),true);const store=createStore(memory());store.save(record('a'),m.units);store.restore(store.preview(JSON.stringify({schemaVersion:2,records:[],mastery:old})));assert(store.data.mastery['g2-add'].reviews.bad.resolved);const malformed=record('invalid');malformed.answers[0].responseMs=-1;assert.throws(()=>store.preview(JSON.stringify({schemaVersion:2,records:[malformed],mastery:{}})));});
test('시드 재현·문항 ID 분리·버전·오개념 선택지·해설 단계',()=>{const p=generateProblem({...cfg,seed:123},c),q=generateProblem({...cfg,seed:123},c);assert.equal(p.conceptId,q.conceptId);assert.notEqual(p.instanceId,q.instanceId);assert.deepEqual(p.options,q.options);assert.equal(p.seed,123);assert.equal(p.generatorVersion,'3');assert(p.explanationSteps.length);assert.equal(p.optionMisconceptions.filter(x=>x==='correct').length,1);});
test('모든 단원 정책·min/max 경계·단계 분포는 별도 검증',()=>{for(const g of c.grades)for(const u of g.units){const means=[];for(const level of u.supportedLevels){const ps=Array.from({length:150},(_,i)=>generateProblem({grade:g.grade,unit:u.id,domain:u.domain,level,seed:900+i},c));for(const rng of [()=>0,()=>.999999999]){const p=generateProblem({grade:g.grade,unit:u.id,level},c,rng);assert(p.operands.every(Number.isFinite));assert(p.operands.every(n=>n>=0));assert(p.answer!=='NaN');}if(['add','subtract'].includes(u.type)){const max=u.policy.levels[level].rangeA[1];for(const p of ps){assert(p.operands[0]<=max);assert(p.operands[1]<=max);if(g.grade===2)assert(p.operands.every(n=>n<=99));if(u.type==='subtract')assert(p.operands[0]>=p.operands[1]);}}if(u.type==='divide'||u.type==='decimalDivide')for(const p of ps)assert.equal(p.operands[0]%p.operands[1],0);if(['fraction','unlikeFraction','fractionMultiply','fractionDivide'].includes(u.type))for(const p of ps){assert(!p.options.some(x=>x.includes('/0')));if(u.type==='fraction')assert(p.operands[0]<p.operands[2]&&p.operands[1]<p.operands[2]);}means.push(ps.reduce((sum,p)=>sum+p.operands.reduce((a,b)=>a+b,0),0)/ps.length);}if(u.supportedLevels.length>1)for(let i=1;i<means.length;i++)assert(means[i]>means[i-1],u.id+' distribution '+means);}});

test('전체 삭제는 v1 원본·백업·격리 데이터까지 삭제 / 기록 0개도 적용',()=>{const st=memory();st.setItem(LEGACY,'{bad');const store=createStore(st);assert(store.data.quarantine.length);store.remove([],true);assert.equal(store.data.quarantine.length,0);assert.equal(st.getItem(LEGACY),null);assert.equal(st.getItem(LEGACY+'.backup'),null);store.save(record('delete'),{});store.remove(['delete'],true);assert.equal(createStore(st).data.records.length,0);});
