import test from 'node:test';import assert from 'node:assert/strict';
import {NEW_WEAPONS,EVOLUTIONS,ULTIMATES,weaponStats,eligibleEvolution} from '../src/v3/weapons-data.js';
import {createWeapons} from '../src/v3/weapons.js';import {SpatialGrid} from '../src/v3/performance.js';
function fixture(){const r={state:{startWeapon:'abacus',newWeapons:{},evolved:{},attackPower:24,mathEnergy:100},player:{x:100,y:100},projectiles:[],floatingTexts:[],enemies:[],v2:{settings:{low:true,reduced:true}},gameNow:()=>5000,distance:(a,b)=>Math.hypot(a.x-b.x,a.y-b.y),burst(){},showToast(){},sfx(){}};const e={x:140,y:100,r:20,hp:10000},battle={grid:new SpatialGrid()};r.enemies=[e];battle.grid.rebuild([e]);return {r,e,battle,w:createWeapons(r,battle)};}
test('10 신규 무기·19 진화·4 합체 및 실질 레벨 성능',()=>{assert.equal(Object.keys(NEW_WEAPONS).length,10);assert(EVOLUTIONS.length>=15);assert(ULTIMATES.length>=4);for(const id of Object.keys(NEW_WEAPONS)){const a=weaponStats(id,1),b=weaponStats(id,5,{},true,2);assert(b.damage>a.damage);assert(b.cooldown<a.cooldown);assert(b.count>a.count);assert(b.range>a.range);}});
test('모든 신규 무기는 공격 판정 또는 렌더링되는 투사체·위험 영역을 생성',()=>{for(const [id,spec]of Object.entries(NEW_WEAPONS)){const {r,e,w}=fixture();w.start();const success=w.attack(id,weaponStats(id,5),5000);assert(success,id);assert(r.projectiles.length||e.hp<10000||w.effects.length,id);if(spec.style==='zone'){w.tick(5000);assert(e.hp<10000);}}});
test('슬롯 상한·진화 조건·상자 중복 방지·합체 에너지 소비',()=>{const {r,w}=fixture();w.start();for(const id of ['star','clock','quill','dice','root'])w.gain(id);assert.equal(Object.keys(w.levels).length,6);assert.equal(w.gain('ruler'),false);const recipe=EVOLUTIONS.find(x=>x.weapon==='abacus');assert(!eligibleEvolution(recipe,w.levels,w.passives,w.evolved));w.levels.abacus=5;w.passives[recipe.passive]=2;assert(w.chest('chest1'));assert.equal(w.chest('chest1'),null);assert(w.evolved.abacus);w.evolved.star=true;w.evolved.satellite=true;w.tick(20000);assert(w.ultimates.galaxy);assert.equal(r.state.mathEnergy,80);w.tick(20001);assert.equal(r.state.mathEnergy,80);});
test('합체 4종은 실제 공격하며 표적이 없으면 에너지를 소비하지 않는다',()=>{for(const u of ULTIMATES){const {r,e,battle,w}=fixture();w.start();for(const id of u.weapons)w.evolved[id]=true;w.tick(20000);assert(w.ultimates[u.id]);assert.equal(r.state.mathEnergy,80);assert(r.projectiles.length||e.hp<10000||w.effects.length);battle.grid.rebuild([]);w.tick(40000);assert.equal(r.state.mathEnergy,80);}});

import {selectUpgradeCards} from '../src/v3/weapons-data.js';
import {bossStats} from '../src/v3/performance.js';
test('강화 선택은 보유 무기를 항상 포함하고 중복 없이 세 장 제공',()=>{const cards=Array.from({length:40},(_,i)=>({slot:'weapon'+i,title:String(i)}));for(let seed=1;seed<100;seed++){let v=seed;const selected=selectUpgradeCards(cards,{weapon39:1},()=>((v=v*1664525+1013904223>>>0)/4294967296));assert.equal(selected.length,3);assert.equal(selected[0].slot,'weapon39');assert.equal(new Set(selected).size,3);}});
test('보스 난이도는 체력·속도·접촉 피해와 최대 체력에 모두 반영',()=>{const base={hp:600,speed:1,damage:20},a=bossStats(base,'easy'),b=bossStats(base),c=bossStats(base,'hard');for(const key of ['hp','speed','damage'])assert(a[key]<b[key]&&b[key]<c[key]);assert.equal(a.hp,a.maxHp);assert.equal(b.damage,20);});
test('별자리 공격은 발사 순간 뒤쪽에 있던 적도 회전 중 타격하고 중복 타격하지 않음',()=>{const {r,e,battle,w}=fixture();w.start();const initial=5000/450;e.x=r.player.x+Math.cos(initial+.65)*110;e.y=r.player.y+Math.sin(initial+.65)*110;battle.grid.rebuild([e]);w.attack('star',{...weaponStats('star',1),count:1},5000);assert.equal(e.hp,10000);w.tick(5293);const hp=e.hp;assert(hp<10000);w.tick(5294);assert.equal(e.hp,hp);});
test('자 레벨 상승은 실제 광선 수를 늘리고 관통 상한도 적용',()=>{const {e,w}=fixture();w.start();w.attack('ruler',weaponStats('ruler',5),5000);assert.equal(w.effects.filter(f=>f.style==='beam').length,3);assert(e.hp<10000);});

import {bossSchedule} from '../src/v3/performance.js';
test('쉬움은 3분 성장 후 보스·중간 보스 4분, 난도별 순서와 3연전 유지',()=>{assert.equal(bossSchedule('easy').boss,180);assert.equal(bossSchedule('easy').mid,240);assert(bossSchedule('easy').boss>bossSchedule().boss);assert(bossSchedule().boss>bossSchedule('hard').boss);assert(bossSchedule('normal',2).boss>bossSchedule('normal',1).boss);});
