import {MAPS} from './MAPS.js';
export function createstate(){ return {
      running: false,
      paused: false,
      difficulty: "normal",
      currentMapKey: "forest",
      map: MAPS.forest,
      worldW: 2800,
      worldH: 1900,
      cameraX: 0,
      cameraY: 0,

      score: 0,
      level: 1,
      exp: 0,
      hp: 120,
      maxHp: 120,
      time: 0,
      combo: 0,
      bestCombo: 0,
      correct: 0,
      wrong: 0,

      mission: null,
      achievements: {},
      feverUntil: 0,
      luckyUntil: 0,
      bossIndex: 0,
      bossWarnings: 0,
      portalCooldown: 0,
      petLevel: 1,
      lastPetShot: 0,

      levelUpPending: false,
      levelUpQueue: 0,

      weaponLevel: 1,
      attackPower: 22,
      fireRate: 490,
      projectileSpeed: 7.5,
      weaponPierce: 0,
      weaponSpread: 1,
      satelliteLevel: 0,
      satelliteAngle: 0,
      laserLevel: 0,
      boomerangLevel: 0,
      chalkRainLevel: 0,

      shield: 0,
      healBonus: 0,
      slowUntil: 0,
      freezeUntil: 0,
      speedUntil: 0,
      magnetUntil: 0,
      doubleScoreUntil: 0,
      hintUntil: 0,
      rainbowUntil: 0,
      eraserUntil: 0,

      lastShot: 0,
      lastSpawn: 0,
      lastQuiz: 0,
      lastItem: 0,
      lastLaser: 0,
      lastBoomerang: 0,
      lastChalkRain: 0,
      quizActive: false,
      currentAnswer: null,
      winTime: 180
    }; }
