import {createPlayUI} from './play-ui.js';
import {mountTeacher} from './v3/teacher.js';
import {MODES,baseMode} from './v3/modes.js';
import {portraitURL} from './v3/graphics.js';
import {PETS,NEW_WORLDS,NEW_CHARACTERS} from './v3/content-data.js';
import {NEW_WEAPONS} from './v3/weapons-data.js';
import {createV3} from './v3/index.js';
import {renderQuestionVisual} from './question-visual.js';
import {generateProblem,equivalent} from './math-engine.js';
import {CHARACTERS,WEAPONS,createCombatV2} from './combat-v2.js';
import {summarize,downloadRecord} from './learning.js';
import {createStore} from './storage.js';
import {createMastery} from './mastery.js';
import {availableUnits,validateConfig} from './configuration.js';
import {APP_VERSION,GENERATOR_VERSION} from './version.js';
import {spriteMarkup,CHARACTER_GEAR,WEAPON_SPRITES} from './sprites.js';
const WEAPON_CATALOG={...WEAPONS,...Object.fromEntries(Object.entries(NEW_WEAPONS).map(([id,w])=>[id,{...w,evolution:w.name+' · 완전 진화'}]))};
const $=id=>document.getElementById(id);
const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function refreshSelectLabels(){for(const select of document.querySelectorAll('#startPanel select')){const label=select.parentElement.querySelector('.selectValue');if(label)label.textContent=select.selectedOptions[0]?.textContent||'선택하세요';}}
function decorateSelects(){const root=$('startPanel');for(const select of root.querySelectorAll('select')){if(select.parentElement.classList.contains('selectField'))continue;const field=document.createElement('div'),value=document.createElement('span');field.className='selectField';value.className='selectValue';value.setAttribute('aria-hidden','true');select.before(field);field.append(select,value);}refreshSelectLabels();root.addEventListener('change',refreshSelectLabels);}
export function createV2(r,curriculum){
 const settings={reduced:matchMedia('(prefers-reduced-motion: reduce)').matches,low:false,font:1};
 const playUI=createPlayUI(r);
 const store=createStore();let mastery=createMastery(store.data.mastery);
 let config={},answers=[],result=null,reviewTick=0,started=0,shown=0,sessionId='',finished=true,input=null,lastHud=-Infinity,notice='';
 const combat=createCombatV2(r,settings),s=r.state;combat.reset();r.v3=createV3(r,settings);
 function syncUnits(){const options=availableUnits({grade:Number($('grade').value),domain:$('domain').value,unit:'all'},curriculum);$('unit').innerHTML='<option value="all">選択 영역 전체</option>'.replace('選択','선택')+options.map(u=>'<option value="'+u.id+'">'+esc(u.name)+'</option>').join('');if(!options.length)notice='이 학년에는 선택한 영역의 단원이 없습니다. 다른 영역을 선택하세요.';else notice='';syncLevels();validate();}
 function syncLevels(){const units=availableUnits(configFromUI(),curriculum);if($('curriculumInfo'))$('curriculumInfo').textContent=curriculum.description+' 현재 선택: '+[...new Set(units.map(u=>u.gradeBand))].join(', ')+' · '+($('unit').value==='all'?units.length+'개 연습 단원':units.map(u=>u.achievementStandards.join(', ')+' · '+u.practiceScope).join(' / '));const supported=[1,2,3,4,5].filter(l=>$('unit').value==='all'||units.every(u=>u.supportedLevels.includes(l)));for(const o of $('mathLevel').options){o.disabled=!supported.includes(Number(o.value));o.hidden=o.disabled;}if(supported.length&&!supported.includes(Number($('mathLevel').value)))$('mathLevel').value=String(supported[0]);refreshSelectLabels();}
 function configFromUI(){return {grade:Number($('grade').value),domain:$('domain').value,unit:$('unit').value,level:Number($('mathLevel').value),auto:$('autoLevel').checked,mode:baseMode($('mode').value),gameMode:$('mode').value,duration:Number($('duration')?.value||8),target:Number($('target').value),limit:Number($('limit').value),character:$('character').value,weapon:$('startingWeapon').value,questionMode:$('questionMode')?.value||'orbs',pet:$('petSelect')?.value||'fairy',map:r.mapSelect.value,combat:r.difficultyEl.value};}
 function validate(){const cfg=configFromUI(),errors=validateConfig(cfg,curriculum);if(!r.v3.progress.data.characters.includes(cfg.character))errors.push('해금한 캐릭터를 선택하세요.');if(!r.v3.progress.data.pets.includes(cfg.pet))errors.push('해금한 펫을 선택하세요.');$('configErrors').textContent=[notice,...errors].filter(Boolean).join(' ');$('startBtn').disabled=errors.length>0;return !errors.length;}
 function saveSettings(){try{localStorage.setItem('math-survival-2.settings',JSON.stringify({...configFromUI(),...settings,muted:r.muted}));}catch(e){$('configErrors').textContent='설정을 저장하지 못했습니다. '+e.message;}}
 function restoreSettings(){try{const raw=localStorage.getItem('math-survival-2.settings');if(!raw)return;const saved=JSON.parse(raw);const errors=validateConfig(saved,curriculum);if(errors.length)throw Error(errors.join(' '));for(const [key,id]of Object.entries({grade:'grade',domain:'domain',level:'mathLevel',mode:'mode',target:'target',limit:'limit',character:'character',weapon:'startingWeapon',combat:'difficulty',map:'mapSelect',pet:'petSelect',questionMode:'questionMode',duration:'duration'}))if(saved[key]!=null)$(id).value=String(saved[key]);if(saved.gameMode)$('mode').value=saved.gameMode;syncUnits();$('unit').value=saved.unit;syncLevels();$('autoLevel').checked=!!saved.auto;settings.reduced=!!saved.reduced;settings.low=!!saved.low;settings.font=[1,1.15,1.3].includes(saved.font)?saved.font:1;$('reducedMotion').checked=settings.reduced;$('lowPower').checked=settings.low;$('fontSize').value=String(settings.font);r.muted=!!saved.muted;}catch(e){notice='저장된 설정을 적용하지 않았습니다. '+e.message;validate();}}
 function applySettings(){document.documentElement.style.setProperty('--reading-scale',settings.font);document.body.classList.toggle('reduce-motion',settings.reduced);document.body.classList.toggle('low-power',settings.low);}
 function layout(){const wrap=$('wrap'),move=(id,ids)=>{const el=document.createElement('div');el.id=id;for(const x of ids)el.append($(x));wrap.prepend(el);return el;};
  move('gameHeader',['hud','playControls','mainMenuBtn','quitGameBtn']);move('learningArea',['questionBox','explanation']);const field=move('playfield',['game']);field.insertAdjacentHTML('beforeend','<div id="bossHUD" hidden></div>');const pane=document.createElement('div');pane.id='canvasPane';pane.append($('game'));field.append(pane);move('answerBar',['answerAccess']);move('touchControls',['joystickZone','dashBtn','skillBtn']);
  const details=document.createElement('details');details.id='gameDetails';details.innerHTML='<summary>미션·무기·효과 보기</summary>';for(const id of ['missionInfo','weaponInfo','activeItems'])details.append($(id));wrap.append(details);
  $('explanation').insertAdjacentHTML('afterend','<button id="continueQuestion" hidden>해설 확인 · 다음 문제</button>');
  $('v2Setup').insertAdjacentHTML('afterend','<p id="configErrors" role="alert"></p><details id="recordManager"><summary>학습 기록·백업 관리</summary><p>같은 브라우저를 사용하는 사람은 기록을 볼 수 있습니다. 수업 후 필요하면 기록을 삭제하세요.</p><div class="row"><button id="backupAll">전체 백업 JSON</button><label>백업 파일<input type="file" id="restoreFile" accept=".json,application/json"></label><button id="deleteSelected">선택 기록 삭제</button><button id="deleteAll">전체 기록 삭제</button></div><p id="backupPreview" role="status"></p><button id="applyRestore" hidden>미리 본 백업 복원 적용</button><div id="deleteConfirm" hidden><p>선택한 기록을 삭제할까요? 숙련도와 복습 상태도 초기화됩니다. 모든 기록을 삭제하면 이관 원본·손상 백업도 제거합니다.</p><button id="confirmDelete">삭제 적용</button><button id="cancelDelete">취소</button></div><div id="historyList"></div><button id="moreHistory">이전 기록 더 보기</button></details><p class="small">앱 '+APP_VERSION+' · 문항 생성기 '+GENERATOR_VERSION+'</p>');
  $('answerBar').insertAdjacentHTML('beforeend','<label id="assistLabel" class="check"><input type="checkbox" id="answerAssist">전투 답안 접근 보조: 버튼을 누르면 구슬로 즉시 이동합니다.</label>');
  $('answerAssist').addEventListener('change',()=>{for(const b of $('answerAccess').querySelectorAll('button'))b.disabled=!$('answerAssist').checked;});
  for(const id of ['target','limit'])$(id).addEventListener('input',validate);
  $('continueQuestion').addEventListener('click',()=>{if(!s.running||!s.explanationPending)return;s.explanationPending=false;s.paused=false;$('continueQuestion').hidden=true;if(answers.length>=config.target)r.endGame(true);else r.spawnQuiz();});
  for(const id of ['unit','mathLevel','mode','target','limit','grade','domain','autoLevel'])$(id).addEventListener('change',()=>{if(id==='unit')syncLevels();validate();});
 }
 function mount(){
  $('v2Setup').innerHTML=`<div class="setupHeading"><span class="eyebrow">MATH SURVIVAL / 새로운 모험</span><h2>오늘의 수학 모험을 골라요</h2><p>정답으로 성장하고, 나만의 무기로 숲을 지켜요.</p></div>
  <div class="setupGrid">
  <label>캐릭터<select id="character">${Object.entries(CHARACTERS).map(([id,c])=>`<option value="${id}">${c.name}</option>`).join('')}</select></label>
  <label>펫<select id="petSelect">${Object.entries(PETS).map(([id,spec])=>`<option value="${id}">${spec.icon} ${spec.name}</option>`).join('')}</select></label><label>게임 모드<select id="mode"><option value="survival">서바이벌 · 무제한 생존</option><option value="explore">수학 탐험 · 교사 설정</option><option value="boss">보스 챌린지 · 3연전</option>${Object.entries(MODES).map(([id,m])=>`<option value="${id}">${m.name}</option>`).join('')}</select></label>
  <label id="durationLabel" hidden>타임 서바이벌 시간<select id="duration"><option value="8">8분</option><option value="15">15분</option><option value="20">20분</option><option value="30">30분</option></select></label><label>학년<select id="grade">${curriculum.grades.map(g=>`<option value="${g.grade}" ${g.grade===3?'selected':''}>${g.grade}학년</option>`).join('')}</select></label>
  <label>학습 영역<select id="domain"><option value="all">전체 영역</option>${Object.entries(curriculum.domains).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}</select></label>
  <label>단원<select id="unit"></select></label>
  <label>문제 표시<select id="questionMode"><option value="orbs">정답 구슬 · 전투 계속</option><option value="popup">문제 팝업 · 전투 정지</option></select></label><label>수학 난이도<select id="mathLevel">${[1,2,3,4,5].map(l=>`<option value="${l}" ${l===2?'selected':''}>${l}단계</option>`).join('')}</select></label>
  <label>시작 무기<select id="startingWeapon">${Object.entries(WEAPON_CATALOG).map(([id,w])=>`<option value="${id}">${w.icon} ${w.name}</option>`).join('')}</select></label>
  <label class="check"><input type="checkbox" id="autoLevel" checked>단원별 새 문항 5개로 자동 난이도</label><small>도형·소수 의미·그래프 비율·가능성 개념 확인은 1단계로 연습합니다.</small>
  </div><div class="curriculumNote"><p id="curriculumInfo"></p><a href="https://www.moe.go.kr/boardCnts/viewRenew.do?boardID=141&amp;boardSeq=93458" target="_blank" rel="noopener">2022 개정 수학과 교육과정 · 교육부 고시 원문</a></div><p class="playPolicy">⏱️ 게임 시간 무제한 · 전투 수학 문제는 답한 뒤 30초 간격</p><fieldset id="teacherSettings"><legend>수학 탐험 · 교사 설정</legend><label>목표 문항 수<input id="target" type="number" value="10" min="1" max="100"></label><label>탐험 제한 시간(초 · 0은 무제한)<input id="limit" type="number" value="0" min="0" max="1800"></label><small>제한 시간은 0 또는 30~1800초입니다. 정답·오답 모두 목표 문항 수에 포함합니다. 오답 피해 없이 해설을 읽고 다음 문제로 넘어갑니다.</small></fieldset>
  <details class="preferences"><summary>⚙️ 화면·접근성 설정</summary><div class="setupGrid"><label class="check"><input id="reducedMotion" type="checkbox">애니메이션 감소</label><label class="check"><input id="lowPower" type="checkbox">저사양 모드</label><label>문제 글자 크기<select id="fontSize"><option value="1">기본</option><option value="1.15">크게</option><option value="1.3">아주 크게</option></select></label></div></details><div id="historySummary" class="history"></div>`;
  for(const [id,map]of Object.entries(NEW_WORLDS)){const option=document.createElement('option');option.value=id;option.textContent=map.name;r.mapSelect.append(option);}layout();r.v3.mount();$('questionSub').insertAdjacentHTML('beforebegin','<div id="questionVisual" hidden></div>');syncUnits();restoreSettings();r.v3.ui.render();decorateSelects();applySettings();r.setMuted(r.muted);
  const previews=document.createElement('div');previews.className='equipmentPreviews';previews.id='equipmentPreviews';$('v2Setup').querySelector('.setupGrid').after(previews);
  const preview=()=>{const c=CHARACTERS[$('character').value],w=WEAPON_CATALOG[$('startingWeapon').value];previews.innerHTML=`<div class="equipmentPreview">${NEW_CHARACTERS[$('character').value]?`<img class="spriteIcon" src="${portraitURL($('character').value)}" alt="" width="64" height="64">`:spriteMarkup(CHARACTER_GEAR[$('character').value])}<div><small>캐릭터 장비</small><strong>${c.name}</strong><span>${c.description}</span></div></div><div class="equipmentPreview">${spriteMarkup(WEAPON_SPRITES[$('startingWeapon').value])}<div><small>시작 무기</small><strong>${w.name}</strong><span>${w.evolution}으로 성장해요</span></div></div>`;};
  $('character').addEventListener('change',()=>{const c=NEW_CHARACTERS[$('character').value];if(c)$('startingWeapon').value=c.weapon;refreshSelectLabels();});for(const id of ['character','startingWeapon'])$(id).addEventListener('change',preview);preview();
  const guide=document.createElement('div');guide.className='spriteGuide';guide.innerHTML=Object.values(r.itemTypes).filter(item=>item.sprite).map(item=>`<div>${spriteMarkup(item.sprite)}<strong>${item.name}</strong><small>${item.desc}</small></div>`).join('');$('tabContent2').append(guide);
  $('startPanel').addEventListener('error',e=>{if(e.target.matches?.('.spriteIcon'))e.target.hidden=true;},true);
  for(const id of ['grade','domain'])$(id).addEventListener('change',syncUnits);
  const modeUI=()=>{$('teacherSettings').hidden=!['explore','dungeon'].includes($('mode').value);$('durationLabel').hidden=$('mode').value!=='timed';};$('mode').addEventListener('change',modeUI);modeUI();mountTeacher(r,curriculum,configFromUI);
  $('reducedMotion').addEventListener('change',e=>{settings.reduced=e.target.checked;applySettings();saveSettings();});$('lowPower').addEventListener('change',e=>{settings.low=e.target.checked;applySettings();saveSettings();});$('fontSize').addEventListener('change',e=>{settings.font=Number(e.target.value);applySettings();saveSettings();});
  $('pauseBtn').addEventListener('click',pause);$('playSound').addEventListener('click',()=>{r.initAudio();r.setMuted(!r.muted);saveSettings();});$('skillBtn').addEventListener('click',combat.skill);
  document.addEventListener('visibilitychange',()=>{if(document.hidden&&s.running&&!s.paused)pause();});
  for(const type of ['JSON','CSV'])$('export'+type).addEventListener('click',()=>downloadRecord(result,type.toLowerCase()));
  $('answerAccess').addEventListener('click',e=>{const btn=e.target.closest('button[data-index]');if(!btn||!s.running||s.paused||(config.mode!=='explore'&&!$('answerAssist').checked))return;const orb=r.answerOrbs[Number(btn.dataset.index)];if(orb){r.player.x=orb.x;r.player.y=orb.y;r.updateCamera();r.resolveAnswer(orb);}});
  history();
  mountHistory();
  playUI.mount();
 }

 function history(){const rows=store.data.records,last=rows.at(-1);$('historySummary').textContent='저장된 모험 '+rows.length+'회'+(last?' · 최근 정답률 '+(last.accuracy==null?'응답 없음':last.accuracy+'%'):'')+' · '+(store.error||'실명 없이 이 브라우저에 저장됩니다.')+(store.data.quarantine.length?' · 손상 기록 '+store.data.quarantine.length+'개를 격리했습니다.':'');if($('historyList'))renderHistory();}
 let historyCount=10,pendingRestore=null,pendingDelete=[],deleteEverything=false;
 function renderHistory(){$('historyList').innerHTML=store.data.records.slice(-historyCount).reverse().map(x=>'<label class="historyRow"><input type="checkbox" value="'+esc(x.sessionId)+'">'+esc(x.date.slice(0,16))+' · '+esc(x.config.grade)+'학년 · '+esc(x.outcome)+' · '+(x.accuracy==null?'응답 없음':x.accuracy+'%')+'</label>').join('');$('moreHistory').hidden=historyCount>=store.data.records.length;}
 function downloadText(text,name){const url=URL.createObjectURL(new Blob([text],{type:'application/json;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
 function mountHistory(){renderHistory();$('moreHistory').onclick=()=>{historyCount+=10;renderHistory();};$('backupAll').onclick=()=>downloadText(store.backup(),'math-survival-backup-v2.json');$('restoreFile').onchange=async e=>{pendingRestore=null;$('applyRestore').hidden=true;try{const file=e.target.files[0];if(!file)return;if(file.size>10*1024*1024)throw Error('백업은 10 MiB 이하여야 합니다.');pendingRestore=store.preview(await file.text());$('backupPreview').textContent='복원 미리 보기: 새 기록 '+pendingRestore.added+'개 · 중복 '+pendingRestore.duplicates+'개 · 복습 상태 포함. 적용 버튼을 눌러야 저장됩니다.';$('applyRestore').hidden=false;}catch(err){$('backupPreview').textContent=err.message;}};
  $('applyRestore').onclick=()=>{if(!pendingRestore)return;const ok=store.restore(pendingRestore);mastery=createMastery(store.data.mastery);pendingRestore=null;$('applyRestore').hidden=true;$('backupPreview').textContent=ok?'복원을 적용했습니다.':store.error;history();};
  const ask=(ids,all=false)=>{pendingDelete=ids;deleteEverything=all;$('deleteConfirm').hidden=!all&&!ids.length;};$('deleteAll').onclick=()=>ask(store.data.records.map(x=>x.sessionId),true);$('deleteSelected').onclick=()=>ask([...$('historyList').querySelectorAll('input:checked')].map(x=>x.value));$('cancelDelete').onclick=()=>{$('deleteConfirm').hidden=true;};$('confirmDelete').onclick=()=>{const ok=store.remove(pendingDelete,deleteEverything);mastery=createMastery(store.data.mastery);$('deleteConfirm').hidden=true;$('backupPreview').textContent=ok?'기록을 삭제했습니다.':store.error;history();};
 }
 function start(){playUI.close();config=configFromUI();answers=[];reviewTick=0;result=null;started=r.gameNow();sessionId=crypto.randomUUID();finished=false;lastHud=-Infinity;s.explanationPending=false;
  s.kills=0;s.mode=config.mode;s.character=config.character;s.winTime=config.mode==='explore'&&config.limit>0?config.limit:Infinity;combat.reset();s.newWeapons[config.weapon]=1;
  const c=CHARACTERS[config.character];s.hp=s.maxHp=c.hp;r.player.speed=c.speed;s.attackPower=c.attack;s.fireRate=c.rate;if(config.character==='guardian')s.shield=2;r.v3.start(config);
  $('explanation').textContent='';$('continueQuestion').hidden=true;$('answerAccess').replaceChildren();$('pauseBtn').textContent='☰';$('pauseBtn').setAttribute('aria-pressed','false');$('assistLabel').hidden=true;saveSettings();r.setMuted(r.muted);r.syncCanvasViewport();r.updateCamera();if(config.mode==='boss'){s.currentMapKey=r.mapSelect.value;r.spawnBoss();}r.spawnQuiz();checkpoint();
 }
 function makeProblem(){const units=availableUnits(config,curriculum),u=units[Math.floor(Math.random()*units.length)];reviewTick++;const rev=reviewTick%3===0?mastery.due(u.id):null;const level=rev?rev.level:mastery.level(u.id,config.level,config.auto,u.supportedLevels);let p;
  for(let tries=0;tries<60;tries++){p=generateProblem({...config,unit:u.id,level,...(config.gameMode==='daily'?{seed:s.dailySeed+reviewTick}: {})},curriculum);if(!rev||p.conceptId!==rev.lastConcept&&!rev.successConcepts.includes(p.conceptId)&&p.operands.join(':')!==rev.operands.join(':'))break;}
  if(rev&&p.conceptId!==rev.lastConcept&&p.operands.join(':')!==rev.operands.join(':')){p.review=true;p.reviewKey=rev.key;if(p.options.indexOf(p.answer)===rev.lastAnswerIndex){p.options.push(p.options.shift());p.optionMisconceptions.push(p.optionMisconceptions.shift());}}else p.review=false;return p;
 }
 function present(problem){r.v3.math.present(problem);renderQuestionVisual(problem,$('questionVisual'));shown=r.gameNow();problem.hintUsed=false;$('explanation').textContent='';$('continueQuestion').hidden=true;$('answerAccess').innerHTML=problem.options.map((value,i)=>'<button '+(config.mode!=='explore'&&!$('answerAssist').checked?'disabled ':'')+'data-index="'+i+'" aria-label="'+esc(value)+' '+(config.mode==='explore'?'답하기':'구슬로 이동')+'">'+(i+1)+'. '+esc(value)+'</button>').join('');}
 function record(orb){const problem=s.problem,now=r.gameNow();if(answers.some(a=>a.instanceId===problem.instanceId))return false;if(!r.v3.math.award(problem,!!orb.correct))return false;const row={...problem,problem:structuredClone(problem),selected:String(orb.value),correct:!!orb.correct,elapsed:Math.round((now-started)/1000),responseMs:Math.round(now-shown),hintUsed:!!problem.hintUsed||now<s.hintUntil,date:new Date().toISOString()};answers.push(row);const u=availableUnits({...config,unit:row.unit},curriculum)[0];mastery.record(row,config.auto,u.supportedLevels);
  $('answerAccess').replaceChildren();$('explanation').textContent=(orb.correct?'✅ 정답! ':'💡 선택 '+orb.value+' → 정답 '+problem.answer+'. ')+problem.explanationSteps.join(' ');s.lastQuiz=now;
 }
 function orbPositions(){const radius=Math.min(38,r.canvas.height/5),padY=radius+4,padX=Math.max(radius+4,46),rows=r.canvas.height<150?2:3,points=[];for(let y=0;y<rows;y++)for(let x=0;x<6;x++){const point={x:s.cameraX+padX+(r.canvas.width-2*padX)*x/5,y:s.cameraY+padY+(r.canvas.height-2*padY)*y/(rows-1)};if(r.distance(point,r.player)>radius+r.player.r+16)points.push(point);}points.sort((a,b)=>r.distance(b,r.player)-r.distance(a,r.player));const chosen=[];for(const point of points){if(chosen.every(p=>r.distance(p,point)>radius*2+5))chosen.push(point);if(chosen.length===4)break;}return chosen;}
 function reposition(){if(!s.quizActive)return;const points=orbPositions();r.answerOrbs.forEach((o,i)=>Object.assign(o,points[i],{r:Math.min(38,r.canvas.height/5)}));}
 function snapshot(outcome,reason){return {...summarize(s,answers,config),sessionId,appVersion:APP_VERSION,curriculumVersion:curriculum.curriculumVersion,generatorVersion:GENERATOR_VERSION,outcome,resultReason:reason,actualLevels:Object.fromEntries([...new Set(answers.map(x=>x.unit))].map(id=>[id,[...new Set(answers.filter(x=>x.unit===id).map(x=>x.level))]]))};}
 function checkpoint(){return store.checkpoint(snapshot('checkpoint','응답마다 저장'),mastery.units);}
 function tick(dt,now){r.v3.tick(dt,now);combat.tick(now);if(s.quizActive&&now<s.hintUntil)s.problem.hintUsed=true;
  if(config.mode==='boss'&&!r.enemies.some(e=>e.boss)){if(s.bossKills>=3){r.endGame(true);return;}const order=['forest','desert','library','ocean','clockwork','sky'],key=order[(order.indexOf(r.mapSelect.value)+s.bossKills)%3];s.currentMapKey=key;s.map=r.MAPS[key];s.worldW=s.map.worldW;s.worldH=s.map.worldH;r.makeDecorations();r.spawnBoss();}
  if(now-lastHud<200)return;lastHud=now;playUI.sync();$('skillBtn').disabled=now<s.skillReady;$('skillBtn').textContent=now<s.skillReady?'스킬 '+Math.ceil((s.skillReady-now)/1000)+'초':'특수 스킬 E';$('playSound').textContent=r.muted?'🔇 소리':'🔊 소리';
  const boss=r.enemies.find(e=>e.boss),el=$('bossHUD');el.hidden=!boss;if(boss){el.textContent=boss.name+' · '+Math.ceil(boss.hp)+' / '+boss.maxHp;el.style.setProperty('--boss-health',(Math.max(0,boss.hp)/boss.maxHp*100)+'%');}
  if(config.mode==='explore')r.missionInfo.textContent='🧭 탐험 '+answers.length+'/'+config.target+'문항 · 시간 무제한';r.updateWeaponInfo();r.weaponInfo.textContent+=' · '+Object.entries(s.newWeapons).filter(([,lvl])=>lvl).map(([key,lvl])=>(s.evolved[key]?WEAPON_CATALOG[key].evolution:WEAPON_CATALOG[key].name)+' Lv.'+lvl).join(' / ');
 }
 function draw(now){combat.draw(now);r.v3.draw(now);}
 function clearInput(){input?.clear();}
 function pause(){if(!s.running||s.mathPopup||s.merchantOpen)return;if(s.levelUpPending||s.explanationPending){if(playUI.isOpen)playUI.close();else playUI.pauseChanged();return;}if(s.paused&&!playUI.isOpen){playUI.pauseChanged();return;}s.paused=!s.paused;if(s.paused)clearInput();playUI.pauseChanged();$('pauseBtn').textContent='☰';$('pauseBtn').setAttribute('aria-pressed',String(s.paused));}
 function finish(won,quit,outcomeOverride){if(finished)return;finished=true;playUI.close();r.v3.math.hide();clearInput();$('answerAccess').replaceChildren();$('continueQuestion').hidden=true;$('bossHUD').hidden=true;
  const outcome=outcomeOverride||(quit?'quit':s.hp<=0?'defeat':config.mode==='explore'&&answers.length<config.target||config.mode==='boss'&&s.bossKills<3?'time-limit':won?'complete':'defeat');
  const titles={interrupted:'메뉴로 이동 · 기록 저장',quit:'게임 종료',defeat:'전투 종료', 'time-limit':'제한 시간 종료',complete:config.mode==='explore'?'목표 문항 완료':config.mode==='boss'?'보스 3연전 완료':'생존 완료'};
  r.v3.finish(outcome);result=snapshot(outcome,titles[outcome]);const saved=store.save(result,mastery.units);history();$('resultTitle').textContent=titles[outcome];$('resultText').textContent=config.mode==='explore'?'수학 탐험 '+answers.length+'/'+config.target+'문항 · 정답률 '+(result.accuracy==null?'응답 없음':result.accuracy+'%'):config.mode==='boss'?'보스 챌린지 '+s.bossKills+'/3 처치':s.map.name+' · '+result.survivalSeconds+'초 생존';
  $('learningReport').innerHTML='<h2>이번 모험의 학습 기록</h2><p>새 문항 '+(result.newAccuracy==null?'응답 없음':result.newAccuracy+'%')+' · 복습 '+(result.reviewAccuracy==null?'응답 없음':result.reviewAccuracy+'%')+' · 힌트 '+result.hintCount+'회</p><h3>단원별 응답</h3>'+Object.entries(result.units).map(([id,u])=>'<p>'+esc(curriculum.grades.flatMap(g=>g.units).find(x=>x.id===id)?.name||id)+' · '+u.correct+'/'+u.total+' · 새 문항 '+u.newCorrect+'/'+u.newTotal+' · 복습 '+u.reviewCorrect+'/'+u.reviewTotal+(u.total<5?' · 표본이 적습니다':'')+'</p>').join('')+'<h3>오답 해설</h3>'+result.reviewProblems.map(w=>'<div class="reviewRow"><strong>'+esc(w.text)+'</strong><p>선택 '+esc(w.selected)+' → 정답 '+esc(w.answer)+'</p><small>'+esc(w.explain)+'</small></div>').join('')+(answers.length===0?'<p>응답한 문항이 없어 정답률을 계산하지 않았습니다.</p>':result.wrong===0?'<p>이번 응답은 모두 맞혔습니다.</p>':'')+'<p role="status">'+(saved?'이 브라우저에 기록을 저장했습니다.':esc(store.error)+' 현재 결과를 JSON/CSV로 내려받으세요.')+'</p>';
 }
 function interrupt(){playUI.close();r.v3.math.hide();if(answers.length)finish(false,false,'interrupted');else{finished=true;r.v3.finish('interrupted');clearInput();store.discardCheckpoint();}}
 function afterAnswer(){playUI.sync();r.v3.modes.answer();checkpoint();if(r.v3.math.afterAnswer())return;if(s.hp<=0){r.endGame(false);return;}if(config.mode==='explore'){s.explanationPending=true;s.paused=true;clearInput();$('continueQuestion').hidden=false;$('continueQuestion').focus();}}
 return {settings,playUI,mount,start,validate,setInput(x){input=x;},clearInput,makeProblem,present,record,orbPositions,reposition,tick,draw,pause,finish,interrupt,afterAnswer,upgrades:()=>[...r.v3.weapons.filterLegacy(combat.upgrades().map(o=>({...o,slot:Object.keys(WEAPONS).find(id=>o.title.startsWith(WEAPONS[id].name))}))),...r.v3.weapons.upgrades()],isCorrect:equivalent,combat,get quizInterval(){return 30000;},get config(){return config;},get answers(){return answers;},get result(){return result;},get store(){return store;},get mastery(){return mastery;}};
}
